# Circleci config
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01 # # recommended linux image - includes Ubuntu 20.04, docker-compose 1.27.4
    steps:
      - run:
          name: "install NPM"
          command: |
                    $sudo npm install -g npm@latest > /dev/null 2>&1 || \
                    npm install -g npm@latest > /dev/null 2<&1
                    npm config -g delete ca
                    $sudo npm install -g newman
                    npm i --package-lock-only
                    npm audit
#                    sudo apt update
#                    sudo apt upgrade -y                    

                    
     
      
          
workflows:
    build_machine:
      jobs:
        - build
